### ISSUE TITLE
Committee list page should have contact emails addresses / forms

### ISSUE THREAD

**Issue by addshore** [SWAuk/website#105]

**Comment by addshore** [comment]
This will require a new col on the committee table which will hold the committee member @swa.co.uk email address.
When filled there should then be a mailto: link in the view?
OR
An alternative would be to link to a form that would email to the committee member? This could also just go to enquiries@swa.co.uk ?

**Comment by oshotton** [comment]
I don't think we should have individual committee members contactable. People should contact us through the SWA FB Chat or via info@swa.co.uk. That was multiple committee members are able to view and reply to messages rather than them getting lost with a no longer active committee member.
