### ISSUE TITLE
Seems like you are able to upload the same qualification twice

### ISSUE THREAD

**Issue by oshotton** [SWAuk/website#125]
![image](https://cloud.githubusercontent.com/assets/5147961/10757888/95b8f684-7ca5-11e5-8003-73be47e13dda.png)

**Comment by addshore** [comment]
How would you expect it to detect duplicates?
A combination of name, expiry date and type?

**Comment by oshotton** [comment]
Yeah sounds good. Even if it was just name and type that would work and if
someone renewed a qualification then they had to delete the old one off the
system first?
