### ISSUE TITLE
Able to unregistered all members from an event

### ISSUE THREAD

**Issue by oshotton** [SWAuk/website#137]
If someone clicks the register all link by accident or mistake then they have to unregister everyone by hand! :-1:

**Comment by addshore** [comment]
Yup ;)

Maybe a confirmation box?
And an unregister all link? ;)

**Comment by oshotton** [comment]
Hadn't thought about a confirmation box, good idea.
But yeah I think at very least an unregister link :)

**Comment by addshore** [comment]
Should be easy (can be done in the same way as the register all link)
