### ISSUE TITLE
Details column of ticket sales is messy

### ISSUE THREAD

**Issue by LukeStorry** [SWAuk/website#210]
The details column should be cleaned up by parsing the string into json then iterating through addons and checking quantity, to prevent this:
![image](https://user-images.githubusercontent.com/5787482/53342476-e91b2200-3905-11e9-9506-e5e8a7a9f22d.png)

Ensuring that changes to the format of the details string still results in addons being shown in the table is important however.

**Comment by LukeStorry** [comment]
Fix would be around line 180 of src/site/views/event/tmpl/default.php

Currently `if ($person['Details'] == "{\"addons\":[]}")` removes the entry for events with no addons, but cases where no addons are bought, or the string is different, failsafes to showing as above screenshot.

**Comment by oshotton** [comment]
Parsing the `$person['Details']` JSON string to a PHP obj seems very sensible.

**Comment by LukeStorry** [comment]
I know you said that in the original PR, and now i agree! 
Iterating through each item in the addons part of that obj to check `qty==0` seems to be the best option
