### ISSUE TITLE
Show notices to committe members when things that should be done have not been

### ISSUE THREAD

**Issue by addshore** [SWAuk/website#97]
For example:

When an event with competitions has run but there have not been any event results entered a few days after the event scream at everyone!

**Comment by Beaker69** [comment]
Yes! And reminders until the task is done!

Sent from my iPhone

On 23 Apr 2015, at 08:55, "addshore" <notifications@github.com> wrote:

For example:

When an event with competitions has run but there have not been any event results entered a few days after the event scream at everyone!
